### ISSUE TITLE
Any plans for multiple treatment vars?

### ISSUE THREAD

**Issue by Garcese** [apoorvalal/ivDiag#5]
Loving the package, I've been specifically looking for an easy way to calculate the AR confidence interval, and this does a good job. I was wondering if there is any way, or at least any plans down the road, to incorporate models with multiple endogenous vars and multiple treatments. 

I really can't find any other R package besides ivmodel that seems to have this feature, and I am really not a fan of how they set up their regression functions so that it takes vectors as inputs instead of var names from a supplied dataframe. So, if there is anyway to do it with ivDiag, that would be great!

I should mention I saw the closed github issue that mentions multiple endogenous vars is allowed but not multiple treatments, which is why I specifically am asking about multiple treatments.

**Comment by apoorvalal** [comment]
Weak-IV inference with multiple treatments becomes [impractical very quickly as the number of treatments grows](https://scholar.harvard.edu/files/wirev_092218-_corrected_0.pdf#page=30.44) (since inversion strategy relies on a grid of first stage effects) and is hard to interpret, so it's not really a priority for this package.
